complete -c wutag -n "__fish_use_subcommand" -s d -l dir -d 'When this parameter is specified the program will look for files starting from provided path, otherwise defaults to current directory. Only applies to subcommands that take a pattern as a positional argument' -r -F
complete -c wutag -n "__fish_use_subcommand" -s m -l max-depth -d 'If provided increase maximum recursion depth of filesystem traversal to specified value, otherwise default depth is 2. Only applies to subcommands that take a pattern as a positional argument' -r
complete -c wutag -n "__fish_use_subcommand" -s o -l output-format -d 'Change the output format to `json` or `yaml`' -r
complete -c wutag -n "__fish_use_subcommand" -s p -l pretty -d 'Make the output pretty (add color and reorder things). This is not recommended when using wutag in scripts'
complete -c wutag -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c wutag -n "__fish_use_subcommand" -f -a "list" -d 'Lists all available tags or files'
complete -c wutag -n "__fish_use_subcommand" -f -a "set" -d 'Tags the files that match the given pattern with specified tags'
complete -c wutag -n "__fish_use_subcommand" -f -a "get" -d 'Retrieve tags of files'
complete -c wutag -n "__fish_use_subcommand" -f -a "rm" -d 'Removes the specified tags of the files that match the provided pattern'
complete -c wutag -n "__fish_use_subcommand" -f -a "clear" -d 'Clears all tags of the files that match the provided pattern'
complete -c wutag -n "__fish_use_subcommand" -f -a "search" -d 'Searches for files that have all of the provided \'tags\''
complete -c wutag -n "__fish_use_subcommand" -f -a "cp" -d 'Copies tags from the specified file to files that match a pattern'
complete -c wutag -n "__fish_use_subcommand" -f -a "edit" -d 'Edits a tag'
complete -c wutag -n "__fish_use_subcommand" -f -a "print-completions" -d 'Prints completions for the specified shell to stdout'
complete -c wutag -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wutag -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from help" -f -a "tags"
complete -c wutag -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from help" -f -a "files"
complete -c wutag -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wutag -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from tags" -s f -l with-files -d 'Should all entries tagged with a tag be shown'
complete -c wutag -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from tags" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from files" -s t -l with-tags -d 'Should the tags of the entry be display'
complete -c wutag -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from files" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from help" -f -a "tags"
complete -c wutag -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from help" -f -a "files"
complete -c wutag -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wutag -n "__fish_seen_subcommand_from set" -s t -l tags -d 'List of tags to tag the entries with' -r
complete -c wutag -n "__fish_seen_subcommand_from set" -s g -l glob -d 'Treat the first path as a glob pattern'
complete -c wutag -n "__fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from get" -s g -l glob -d 'Treat the first path as a glob pattern'
complete -c wutag -n "__fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from rm" -s t -l tags -r
complete -c wutag -n "__fish_seen_subcommand_from rm" -s g -l glob -d 'Treat the first path as a glob pattern'
complete -c wutag -n "__fish_seen_subcommand_from rm" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "tags" -d 'Remove tags completely'
complete -c wutag -n "__fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "files" -d 'Remove all tags from specified files'
complete -c wutag -n "__fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "cache"
complete -c wutag -n "__fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wutag -n "__fish_seen_subcommand_from clear; and __fish_seen_subcommand_from tags" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from clear; and __fish_seen_subcommand_from files" -s g -l glob -d 'Treat the first path as a glob pattern'
complete -c wutag -n "__fish_seen_subcommand_from clear; and __fish_seen_subcommand_from files" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from clear; and __fish_seen_subcommand_from cache" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from clear; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "tags" -d 'Remove tags completely'
complete -c wutag -n "__fish_seen_subcommand_from clear; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "files" -d 'Remove all tags from specified files'
complete -c wutag -n "__fish_seen_subcommand_from clear; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "cache"
complete -c wutag -n "__fish_seen_subcommand_from clear; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wutag -n "__fish_seen_subcommand_from search" -s a -l any -d 'If set to \'true\' all entries containing any of provided tags will be returned'
complete -c wutag -n "__fish_seen_subcommand_from search" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from cp" -s g -l glob -d 'Treat the first path as a glob pattern'
complete -c wutag -n "__fish_seen_subcommand_from cp" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from edit" -s c -l color -d 'Set the color of the tag to the specified color. Accepted values are hex colors like `0x000000` or `#1F1F1F` or just plain `ff000a`. The colors are case insensitive meaning `1f1f1f` is equivalent to `1F1F1F`' -r
complete -c wutag -n "__fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from print-completions" -s h -l help -d 'Print help'
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "list" -d 'Lists all available tags or files'
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "set" -d 'Tags the files that match the given pattern with specified tags'
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "get" -d 'Retrieve tags of files'
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "rm" -d 'Removes the specified tags of the files that match the provided pattern'
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "clear" -d 'Clears all tags of the files that match the provided pattern'
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "search" -d 'Searches for files that have all of the provided \'tags\''
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "cp" -d 'Copies tags from the specified file to files that match a pattern'
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "edit" -d 'Edits a tag'
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "print-completions" -d 'Prints completions for the specified shell to stdout'
complete -c wutag -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from rm; and not __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from cp; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from print-completions; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c wutag -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files" -f -a "tags"
complete -c wutag -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files" -f -a "files"
complete -c wutag -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache" -f -a "tags" -d 'Remove tags completely'
complete -c wutag -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache" -f -a "files" -d 'Remove all tags from specified files'
complete -c wutag -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from clear; and not __fish_seen_subcommand_from tags; and not __fish_seen_subcommand_from files; and not __fish_seen_subcommand_from cache" -f -a "cache"
