git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
# https://github.com/iamverysimp1e/dots/blob/main/configs/lazygit/config.yml#L29
gui:
  theme:
    showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  showIcons: false

promptToReturnFromSubprocess: false
disableStartupPopups: true
notARepository: 'quit'
