session_name = "dev"
number_of_panes = 2
commands = ["nvim", "fish"]

[pythonupdates]
number_of_panes = 2
session_name = "pyupdates"
commands = ["python -m pip install -U wheel pip pipx", "pipx list && pipx upgrade-all"]

[systemupdate]
number_of_panes = 4
layout="376f,147x39,0,0{73x39,0,0[73x24,0,0,0,73x14,0,25,4],73x39,74,0[73x34,74,0,1,73x4,74,35,5]}"
session_name = "updates"
commands = ["nix-channel --update; nix-env -iA nixpkgs.nix nixpkgs.cacert; nix-env -u", "rustup upgrade; cargo +nightly install-update --all && cargo +nightly install --git https://github.com/neovide/neovide neovide && cargo install --git https://github.com/tazjin/nixfd nixfd && cargo install russ --git https://github.com/ckampfe/russ", "home-manager switch", "nixfd"]

[systemupdate-cleanup]
number_of_panes = 2
session_name = "cleanup"
commands = ["nix-collect-garbage", "nix-env --delete-generations old"]

