session_name = "dev"
number_of_panes = 2
commands = ["nvim", "fish"]

[pythonupdates]
number_of_panes = 2
session_name = "pyupdates"
commands = ["python -m pip install -U wheel pip pipx", "pipx list && pipx upgrade-all"]

[systemupdate]
number_of_panes = 3
session_name = "updates"
layout = "71b7,160x40,0,0[160x21,0,0{80x21,0,0,16,79x21,81,0,18},160x18,0,22,12]"
commands = ["pacui", "nixfd", "topgrade --skip-notify --disable chezmoi --disable-predefined-git-repos --no-retry"]

[systemupdate-cleanup]
number_of_panes = 2
session_name = "cleanup"
commands = ["nix-collect-garbage", "nix-env --delete-generations old"]

[gotty]
session_name = "gotty"
# number_of_panes = 2
# commands = ["gotty ~/.config/dmux/gotty.sh", "btop"]
number_of_panes = 1
commands = ["gotty btop"]

[audio]
session_name = "audio"
number_of_panes = 3
layout = "166d,160x39,0,0[160x19,0,0,0,160x19,0,20{80x19,0,20,6,79x19,81,20,7}]"
commands = ["navi --query 'tmux dmuxaudio'", "pulsemixer", "bluetuith"]

[monitor]
session_name = "monitor"
number_of_panes = 2
layout = "e64a,160x39,0,0{97x39,0,0,24,62x39,98,0,25}"
commands = ["btop", "htop"]
