#import = ["/home/rithviz/.config/alacritty/font.toml", "/home/rithviz/.config/alacritty/colors.toml"]
import = ["/home/rithviz/.config/alacritty/font.toml"]
live_config_reload = true

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 9000

[window]
decorations = "none"
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 1
startup_mode = "Fullscreen"

[window.class]
general = "Alacritty"
instance = "Alacritty"
